import os
import json
import subprocess
import shutil
import jinja2
from typing import TypedDict, List
from pydantic import BaseModel, Field

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.memory import MemorySaver
from dotenv import load_dotenv

load_dotenv()

engine_dir = os.path.dirname(__file__)
root_dir = os.path.dirname(engine_dir)

# --- PYDANTIC MODELS ---
class JobMetadata(BaseModel):
    company_name: str = Field(description="Name of the company hiring")
    role_name: str = Field(description="Title of the role")
    job_summary: str = Field(description="A concise 2-3 sentence summary of the job description.")
    key_requirements: List[str] = Field(description="A bulleted list of 3-5 key technical and soft requirements for the role.")
    eligibility_passed: bool = Field(description="True if the candidate meets absolute hard requirements (visa/location/language). False if there's a hard mismatch.")
    eligibility_reason: str = Field(description="If eligibility_passed is False, explain the exact hard requirement mismatch. If True, leave empty.")

class StrategyQuestion(BaseModel):
    question: str = Field(description="The question to ask the user.")
    options: List[str] = Field(description="2-4 multiple-choice options for the user.")

class StrategyResult(BaseModel):
    fit_assessment: str = Field(description="A clear assessment of how well the candidate fits the role (e.g., 'Strong Fit', 'Moderate Fit', 'Low Fit'), including a brief explanation so the candidate can save time if it's a massive stretch.")
    strategy_plan: str = Field(description="High-level plan mapping the candidate's experience to the role.")
    role_philosophy: str = Field(description="One sentence capturing the underlying tension or value the JD implies based on 'Who you are' (e.g. 'this role values a validated no over a shipped yes').")
    sharpest_project_insight: str = Field(description="The most honest or surprising finding from the top-matched project, not its headline metric.")
    targeted_questions: List[StrategyQuestion] = Field(description="1-2 targeted questions to ask the candidate to confirm preferences before drafting.")

class SectionItem(BaseModel):
    title: str
    subtitle: str
    date: str
    url: str
    context: str
    bullets: List[str]

class Section(BaseModel):
    title: str
    type: str = Field(description="Must be 'skills', 'education', 'projects', 'work_experience', or 'custom'")
    items: List[SectionItem]

class CVData(BaseModel):
    reasoning: str = Field(description="Explain your logic for selecting and tailoring items across all sections, and how you injected ATS keywords naturally.")
    professional_summary: str = Field(description="The tailored professional summary paragraph.")
    sections: List[Section] = Field(description="List of ALL tailored sections. Must include every section from the baseline CV.")

class ReviewResult(BaseModel):
    passed: bool = Field(description="True if the draft passes all rules, False otherwise.")
    feedback: str = Field(description="Feedback on what needs to be fixed if passed is False. Empty if passed is True.")

class CoverLetterOutput(BaseModel):
    paragraphs: List[str] = Field(description="The cover letter paragraphs, including salutation and sign-off.")

# --- STATE DEFINITION ---
class AgentState(TypedDict):
    job_description: str
    generic_cv_raw: str
    company_name: str
    role_name: str
    job_summary: str
    key_requirements: list
    eligibility_passed: bool
    eligibility_reason: str
    strategy_plan: str
    role_philosophy: str
    sharpest_project_insight: str
    strategy_questions: list
    user_strategy_answers: str
    tailored_cv: dict
    cover_letter_paragraphs: list   # generated by cover_letter_node, separate from CV tailor
    review_feedback: str
    revision_count: int
    user_feedback: str
    custom_instructions: str
    generate_cover_letter: bool

# --- LLM INITIALIZATION ---
def get_llm(): return ChatOpenAI(model="gpt-4o", temperature=0.2, api_key=os.environ.get("OPENAI_API_KEY"))
def get_llm_cl(): return ChatOpenAI(model="gpt-4o", temperature=0.5, api_key=os.environ.get("OPENAI_API_KEY"))

def get_llm_json(): return get_llm().with_structured_output(CVData)
def get_llm_review(): return get_llm().with_structured_output(ReviewResult)
def get_llm_setup(): return get_llm().with_structured_output(JobMetadata)
def get_llm_cl_out(): return get_llm_cl().with_structured_output(CoverLetterOutput)

# --- NODES ---

def get_lessons(scope_filter=None):
    lessons_path = os.path.join(engine_dir, 'data', 'lessons.json')
    if os.path.exists(lessons_path):
        try:
            with open(lessons_path, 'r', encoding='utf-8') as f:
                all_lessons = json.load(f)
                if not scope_filter:
                    return [l["lesson"] if isinstance(l, dict) else l for l in all_lessons]
                filtered = []
                for l in all_lessons:
                    if isinstance(l, dict):
                        if any(s in l.get("scope", []) for s in scope_filter):
                            filtered.append(l["lesson"])
                    else:
                        filtered.append(l) # fallback for old flat strings
                return filtered
        except: pass
    return []

class LessonResult(BaseModel):
    lesson: str = Field(description="A clear, generalized rule extracted from the feedback to apply to all future applications.")
    scope: List[str] = Field(description="Which document this rule applies to. Options: 'CV', 'Cover_Letter', 'General'.")

def extract_lesson(user_feedback: str):
    existing_lessons = get_lessons()
    existing_text = "\n".join(existing_lessons) if existing_lessons else "None"
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", f"Extract a clear, concise rule for future CV/Cover Letter generation based on this user feedback. E.g. 'Never use em-dashes', 'Always highlight ComfyUI'.\n\nCRITICAL: Do NOT extract a rule if it is already covered by the EXISTING RULES below. If it is redundant, return an empty string for the lesson.\n\nEXISTING RULES:\n{{existing_text}}"),
        ("user", "{feedback}")
    ])
    chain = prompt | get_llm().with_structured_output(LessonResult)
    res = chain.invoke({"feedback": user_feedback, "existing_text": existing_text})
    
    if not res.lesson or not res.lesson.strip():
        return
        
    lessons_path = os.path.join(engine_dir, 'data', 'lessons.json')
    try:
        with open(lessons_path, 'r', encoding='utf-8') as f:
            lessons = json.load(f)
    except:
        lessons = []
        
    valid_scopes = [s for s in res.scope if s in ["CV", "Cover_Letter", "General"]]
    if not valid_scopes: valid_scopes = ["General"]
    
    lessons.append({"lesson": res.lesson, "scope": valid_scopes})
    with open(lessons_path, 'w', encoding='utf-8') as f:
        json.dump(lessons, f, indent=2)

def setup_node(state: AgentState):
    prompt = ChatPromptTemplate.from_messages([
        ("system", "Read the Job Description and the Generic CV provided below. Extract the company name, role name, job summary, and key requirements. Finally, evaluate the candidate's Eligibility (checking for hard mismatches in visa/location/languages). Output strictly the requested JSON."),
        ("user", "Job Description:\n{job_description}\n\nGeneric CV:\n{generic_cv}")
    ])
    chain = prompt | get_llm_setup()
    res = chain.invoke({"job_description": state["job_description"], "generic_cv": state["generic_cv_raw"]})
    
    company = "Unknown_Company"
    role = "Unknown_Role"
    if res:
        company = res.company_name.strip() if res.company_name and res.company_name.strip() else "Unknown_Company"
        role = res.role_name.strip() if res.role_name and res.role_name.strip() else "Unknown_Role"
    
    return {
        "company_name": company, 
        "role_name": role,
        "job_summary": res.job_summary if res else "",
        "key_requirements": res.key_requirements if res else [],
        "eligibility_passed": res.eligibility_passed if res else True,
        "eligibility_reason": res.eligibility_reason if res else ""
    }

def strategist_node(state: AgentState):
    lessons = get_lessons(["General"])
    lessons_prompt = f"\n\nPAST LESSONS (MUST OBEY):\n{json.dumps(lessons, indent=2)}" if lessons else ""
    prompt = ChatPromptTemplate.from_messages([
        ("system", f"You are an expert tech recruiter. Read the Job Description and the Generic CV. First, assess the candidate's 'fit' for the role to save them time if it's a stretch. Then formulate a strategy mapping their experience to the role. Identify exact mandatory ATS keywords. Highlight the top projects to include.\n\nPay extremely close attention to the 'Who you are' or 'About you' sections of the Job Description. Do not just pattern-match on technical keywords; deeply analyze the specific type of problem solver they are looking for (e.g. benchmarking, assessing feasibility, autonomous work). Finally, generate 1-2 targeted questions with multiple-choice options to ask the candidate to confirm preferences before drafting.\n\nCRITICAL RULE 1: Do NOT use markdown asterisks (**) for bolding text anywhere in your output. Use plain text only.\nCRITICAL RULE 2: Even if the candidate is completely unqualified or ineligible, you MUST still output the required JSON strategy structure without failure. Simply provide a 'Low Fit' assessment and do your best to formulate a generic strategy. Do NOT output a refusal.{{lessons_prompt}}"),
        ("user", "Job Description:\n{job_description}\n\nGeneric CV:\n{generic_cv}")
    ])
    chain = prompt | get_llm().with_structured_output(StrategyResult)
    res = chain.invoke({"job_description": state["job_description"], "generic_cv": state["generic_cv_raw"], "lessons_prompt": lessons_prompt})
    
    questions_dicts = [q.model_dump() for q in res.targeted_questions]
    return {
        "strategy_plan": f"**Fit Assessment:**\n{res.fit_assessment}\n\n**Strategy Plan:**\n{res.strategy_plan}", 
        "role_philosophy": res.role_philosophy,
        "sharpest_project_insight": res.sharpest_project_insight,
        "strategy_questions": questions_dicts, 
        "revision_count": state.get("revision_count", 0)
    }

def tailor_node(state: AgentState):
    rules = """
    STRICT RULES:
    0. USER OVERRIDE: If the user's Supplemental Candidate Context (custom instructions or strategy answers) or Feedback explicitly contradicts any of the strict rules below (e.g., asking to delete an item, add a specific skill, or restructure a section), the user's instructions take ABSOLUTE PRECEDENCE. You must obey the user's override.
    1. DO NOT invent or hallucinate any skills, metrics, or technologies not present in the generic CV. This STRICTLY APPLIES to the Professional Summary as well; you cannot claim the candidate has experience in a specific domain if it is absent from the generic CV.
    2. NEVER use em dashes (---) in paragraph text.
    3. For the 'projects' section ONLY: You MUST select exactly 5 projects (always including the Master's Thesis and BSc Final-Year Project). You MUST reorder the 5 selected projects so that the most relevant projects for this specific role appear at the top.
    4. For ALL OTHER sections: You MUST include every single item from the generic CV exactly as they appear (do not delete or add items) UNLESS explicitly instructed otherwise by the user. Only rewrite their bullet points to inject ATS keywords if naturally possible.
    5. ATS KEYWORD STRATEGY: You may only inject ATS keywords if they logically fit into the existing narrative of the item. Do NOT fundamentally change the story, scope, or technical achievements of any item. 
    6. The original item's authenticity must never be compromised. 
    7. NEVER change the 'Tools Used' or similar context line (e.g., "ReactJS, Firebase, Agile, Git" MUST remain identical). Only weave keywords into the bullet points.
    8. NO MARKDOWN FORMATTING: Do NOT use markdown bolding (e.g. **keyword**) or italics anywhere in your output. Output raw, plain text only.
    9. IGNORING COVER LETTER FEEDBACK: If the user's feedback specifically mentions the Cover Letter and does NOT mention the CV, ignore the feedback and keep the CV changes minimal or identical to previous iterations.

    BULLET VOICE (applies to bullets only, not Professional Summary):
    10. BAN empty intensifiers: "successfully," "effectively," "expertly," "robust," "seamlessly," "cutting-edge," "leveraged" (use "used" or "built with" instead), "various," "comprehensive." If a bullet works without the adjective, the adjective goes.
    11. VARY the opening verb across the bullets. Do not let three bullets in a row open with "Built" or "Developed." Rotate: Built, Designed, Reduced, Ran, Architected, Deployed, Automated, Shipped, Coordinated, Led, etc., chosen for what's actually true of that bullet, not at random.
    12. Metrics stay embedded in the sentence that earns them, never appended as a dangling clause. Not "Built a classifier, achieving 94% accuracy" as a generic tail; only keep the metric tail if the sentence has nowhere more natural to put it. Prefer working it into the clause: "Fine-tuned BERT for binary classification, achieving 94% accuracy" only if that's the most natural phrasing already in the generic CV; otherwise restructure minimally.
    13. No paragraph-style summarizing inside a bullet. Each bullet is one concrete action plus its concrete result. Cut any bullet that ends in a vague capstone clause like "...improving overall system performance" or "...enhancing the user experience" unless that exact outcome is named with specifics from the generic CV.

    PROFESSIONAL SUMMARY VOICE:
    14. Open with role/credential plus one concrete specialization, not a values statement. Avoid "passionate about," "dedicated to," "proven track record."
    15. Keep sentences short. 3-4 sentences total, no sentence over ~30 words.
    16. EVENT EXAGGERATION: NEVER pluralize single events or projects into "roles" or "experiences" (e.g., do not say "client-facing roles" if the generic CV only shows a single event). Stick exactly to the scale of the experience described.
    """
    
    
    user_strategy = state.get('user_strategy_answers', '')
    user_feedback = state.get('user_feedback', '')
    
    cv_context = state.get("generic_cv_raw", "")
    if user_strategy or user_feedback:
        cv_context += "\n\n--- SUPPLEMENTAL CANDIDATE CONTEXT (From User's Custom Instructions & Feedback) ---\n"
        cv_context += "The following information is strictly factual candidate data provided by the user and MUST be treated as if it were part of the Generic CV.\n"
        cv_context += "CRITICAL INSTRUCTION: You MUST explicitly integrate the facts from this Supplemental Context directly into the CV content (e.g., within the Professional Summary, Project Context, or Bullets). Do NOT ignore this data.\n"
        if user_strategy:
            cv_context += f"\nUser Strategy Answers (MUST INTEGRATE):\n{user_strategy}\n"
        if user_feedback:
            cv_context += f"\nUser Feedback on Previous Draft (CRITICAL TO APPLY):\n{user_feedback}\n"
    
    lessons = get_lessons(["CV", "General"])
    lessons_prompt = f"\n\nPAST LESSONS (MUST OBEY):\n{json.dumps(lessons, indent=2)}" if lessons else ""
    
    previous_cv = state.get("tailored_cv", {})
    previous_cv_prompt = f"\n\nPrevious Tailored CV (Apply feedback to THIS version):\n{json.dumps(previous_cv, indent=2)}" if previous_cv and user_feedback else ""
    
    prompt = ChatPromptTemplate.from_messages([
        ("system", f"You are an expert CV writer. Your ONLY task is to rewrite the CV JSON (professional summary and all sections) to best match this role. Do NOT write any cover letter content. \n\n{{rules}}{{lessons_prompt}}"),
        ("user", "Job Description:\n{job_description}\n\nStrategist's Plan:\n{strategy_plan}\n\nGeneric CV JSON (Including Supplemental Data):\n{generic_cv}{previous_cv_prompt}")
    ])
    
    chain = prompt | get_llm_json()
    res = chain.invoke({
        "job_description": state.get("job_description", ""),
        "strategy_plan": state.get("strategy_plan", ""),
        "generic_cv": cv_context,
        "previous_cv_prompt": previous_cv_prompt,
        "rules": rules,
        "lessons_prompt": lessons_prompt
    })
    
    return {"tailored_cv": res.model_dump(), "revision_count": state.get("revision_count", 0) + 1}

def reviewer_node(state: AgentState):
    rules = """
    You are a strict QA Reviewer. Check the newly tailored CV against the generic CV.
    Check for:
    1. Hallucinations: Did the tailor invent any technologies or metrics not in the generic CV?
    2. Em-dashes: Are there any em-dashes (---) in the text?
    3. Markdown: Are there any markdown asterisks (**) used for bolding? If so, FAIL.
    4. Banned Phrases (Rule 14): Check the Professional Summary. If it contains "passionate about", "dedicated to", or "proven track record", FAIL.
    5. Event Exaggeration: Did the tailor pluralize a single event into "roles" or "experiences" (e.g. claiming "client-facing roles" when the CV only shows a single pitch)? If so, FAIL.
    
    If it fails ANY of these, return passed=False and explain exactly what to fix. If it passes, return passed=True.
    """
    prompt = ChatPromptTemplate.from_messages([
        ("system", rules),
        ("user", "Generic CV:\n{generic_cv}\n\nTailored CV:\n{tailored_cv}")
    ])
    chain = prompt | get_llm_review()
    res = chain.invoke({
        "generic_cv": state["generic_cv_raw"],
        "tailored_cv": json.dumps(state["tailored_cv"])
    })
    return {"review_feedback": res.feedback if not res.passed else "PASS"}

def cover_letter_node(state: AgentState):
    """Dedicated node for cover letter generation."""
    if not state.get("generate_cover_letter"):
        return {"cover_letter_paragraphs": []}

    tailored = state.get("tailored_cv", {})
    # Provide the full CV so it can see education, custom projects, languages, etc.
    cv_context = json.dumps(tailored, indent=2)
    professional_summary = tailored.get("professional_summary", "")

    lessons = get_lessons(["Cover_Letter", "General"])
    lessons_text = "\n".join(f"- {l}" for l in lessons) if lessons else ""
    lessons_prompt = f"\n\nPAST LESSONS (MUST OBEY):\n{lessons_text}" if lessons_text else ""
    
    candidate_name = "[Candidate Name]"
    try:
        generic_raw = state.get("generic_cv_raw", "")
        if generic_raw:
            baseline_data = json.loads(generic_raw)
            candidate_name = baseline_data.get("personal_info", {}).get("name", "[Candidate Name]")
    except Exception:
        pass

    user_strategy = state.get("user_strategy_answers", "")
    strategy_prompt = f"\n\nUSER'S CUSTOM INSTRUCTIONS:\n{user_strategy}" if user_strategy else ""
    
    user_feedback = state.get("user_feedback", "")
    feedback_prompt = f"\n\nUSER FEEDBACK FROM PREVIOUS DRAFT (CRITICAL: You MUST explicitly address and apply EVERY SINGLE point mentioned in the user feedback below. Do not ignore any part of the request.):\n{user_feedback}\n(If this feedback applies only to the CV, ignore it and write a standard cover letter.)" if user_feedback else ""

    cl_feedback = state.get("cl_review_feedback", "")
    cl_feedback_prompt = f"\n\nCRITICAL FEEDBACK FROM PROOFREADER (YOU MUST FIX THESE HALLUCINATIONS/ERRORS): {cl_feedback}" if cl_feedback and cl_feedback != "PASS" else ""
    
    role_philosophy = state.get("role_philosophy", "")
    sharpest_insight = state.get("sharpest_project_insight", "")

    prompt = ChatPromptTemplate.from_messages([
        ("system", f"""You are writing a cover letter for a job application. Write exactly 6 paragraphs.

DELIVERABLE OVERRIDE: Before generating the standard framework below, scan the Job Description for any explicit structural deliverable requests (e.g., "describe your most complex project", "answer these 3 questions", "explain your philosophy on X"). If the JD requests specific answers, you MUST fulfill those requirements within the body of the cover letter. Fulfilling the JD's explicit instructions takes absolute precedence over the standard 6-paragraph framework below.

FRAMEWORK:
1. Salutation: Match the language of the Job Description. If the JD is in Swedish, use a Swedish greeting (e.g. "Hej [Company]-team,"). If the JD is in English, use an English greeting (e.g. "Dear Hiring Team,"). If the user provided custom instructions for a specific greeting, YOU MUST USE THEIR EXACT GREETING.
2. Hook: Why THIS company's specific industry and business (as described in the Job Description) is compelling.
   Read the Job Description. The Hook is about THEIR world: their sector, their mission, their problem space.
   Do NOT write about the candidate's project topics or academic domains.
3. Match: Connect the role's philosophy ({role_philosophy}) to the candidate's sharpest project insight ({sharpest_insight}) directly. The match should feel conceptual, not just technical overlap. Include concrete metrics only if they exist in the Candidate's CV. DO NOT INVENT OR ROUND METRICS. If you use a metric, COPY IT EXACTLY AS WRITTEN in the Candidate's CV. Use them only in service of the conceptual point, not as a standalone credential dump.
4. Curiosity: One specific technical challenge in this role the candidate wants to explore. Frame as genuine curiosity, not a solution pitch. The curiosity should reveal something about the candidate's own working style or instincts, not just name a topic. CRITICAL: Do NOT name specific tools, technologies, or vendor platforms from the Job Description in this paragraph unless they are also explicitly listed in the candidate's CV data. Express curiosity conceptually, about a problem or design tension, not by citing a JD tool stack the candidate hasn't worked with.
5. Fit: Short close referencing this company's actual mission and work environment. State availability. Include exactly one honest limitation or gap, framed plainly. After stating the honest limitation, immediately reframe by naming the specific underlying skill that still transfers despite the gap. End with a natural, varied transition to the sign-off. Do NOT use any phrase starting with 'Let's...' or 'I look forward to...'. Simply state your interest in their specific problem space.
6. Sign-off and Name: Match the language of the Job Description. If Swedish, use "Vänliga hälsningar,\n\n{candidate_name}". If English, use "Best regards,\n\n{candidate_name}". If the user provided custom instructions for a specific sign-off, YOU MUST USE THEIR EXACT SIGN-OFF.

VOICE AND RHYTHM (this is what makes it sound human, follow it exactly):
- Use contractions throughout: "I'm," "don't," "that's," "isn't." A cover letter with zero contractions reads as AI-generated.
- Vary sentence length hard. Follow a long sentence with a short one. A fragment is fine if it lands. E.g. "Chasing that down taught me X. That's basically the job, as far as I can tell."
- NEVER use em dashes. When you need a connecting clause, use a comma or "and" instead. E.g. not "the model failed quietly—not loudly" but "the model failed quietly, not loudly."
- AVOID triadic lists ("X, Y, and Z" or "not A, not B, but C" repeated more than once per letter). This is the single biggest AI tell. One paragraph can have rhythm-of-three at most.
- Open the Hook paragraph with a direct, concrete observation about the company's core problem space. Vary this opener organically for every letter. DO NOT reuse generic openers or boilerplate phrases across different letters.
- Do NOT use colons (:) anywhere in the letter.
- Do not summarize what you just said at the end of a paragraph. Let paragraphs end on the most specific, concrete detail, not a wrap-up sentence.

BANNED PHRASES (reject and rewrite if any appear):
- "I am excited to," "I am passionate about," "I would be thrilled," "I am thrilled"
- "in today's fast-paced/rapidly evolving," "cutting-edge," "leverage," "synergy"
- "I believe that," "I am confident that"
- Any sentence starting with "Moreover," "Furthermore," "Additionally" as a paragraph opener
- Closing with "I look forward to the opportunity to discuss" verbatim, use a more specific, direct ask instead

RULES:
- Each paragraph 40-60 words. Total 180-220 words.
- EXPLICIT GROUNDING CONSTRAINT: Every substantive claim about the company/role MUST strictly cite or paraphrase a specific line from the provided Job Description text. Do not infer company focus from title keywords alone. Do not invent details about their products. Do NOT invent or fabricate the company's beliefs, values, or philosophies. Any claim about what the company values MUST be explicitly stated in the Job Description text. Base everything exclusively on the provided Job Description.
- NO HALLUCINATIONS: You are strictly forbidden from inventing metrics, percentages, tools, frameworks, or outcomes that are not explicitly written in the candidate's provided CV. If the JD mentions a tool the candidate has not used, you must either use the candidate's actual tool or omit the reference entirely. This rule applies to ALL four paragraphs including the Curiosity paragraph. Do NOT name any tool, technology, or platform that appears only in the Job Description and not in the candidate's CV data. 
- EXCEPTION TO NO HALLUCINATIONS: You may include outside tools, languages, or facts ONLY IF the user explicitly requested them in the USER'S CUSTOM INSTRUCTIONS below. In that case, prioritize the user's instructions over the CV.
- The Hook MUST be grounded in what the company described in the Job Description actually does.{lessons_prompt}{strategy_prompt}{feedback_prompt}{cl_feedback_prompt}"""),
        ("user", "Company: {company_name}\nRole: {role_name}\n\nJob Description:\n{job_description}\n\nCandidate Professional Summary:\n{professional_summary}\n\nCandidate's Full Tailored CV JSON:\n{cv_context}")
    ])

    chain = prompt | get_llm_cl_out()
    res = chain.invoke({
        "company_name": state.get("company_name", ""),
        "role_name": state.get("role_name", ""),
        "job_description": state.get("job_description", ""),
        "professional_summary": professional_summary,
        "cv_context": cv_context,
        "role_philosophy": role_philosophy,
        "sharpest_insight": sharpest_insight,
        "candidate_name": candidate_name,
        "lessons_prompt": lessons_prompt,
        "strategy_prompt": strategy_prompt,
        "feedback_prompt": feedback_prompt,
        "cl_feedback_prompt": cl_feedback_prompt
    })
    return {"cover_letter_paragraphs": res.paragraphs, "user_feedback": ""}

# cl_reviewer_node removed: the LLM critic was producing systematic false positives
# (flagging non-existent colons, treating honestly-disclosed candidate gaps as hallucinations).
# The human-review interrupt before compiler_node serves as the quality gate instead.

def compiler_node(state: AgentState):
    tailored_cv = state.get("tailored_cv", {})
    
def _get_app_root_dir(company_name, role_name):
    import re
    def sanitize(text):
        text = text.replace(" ", "_")
        return re.sub(r'[\\/*?:"<>|]', "", text)
    c_name = sanitize(company_name)
    r_name = sanitize(role_name)
    return os.path.join(root_dir, "Applications", f"{c_name}_{r_name}"), c_name

def compile_cv_pdf(cv_data, company_name, role_name):
    app_root_dir, c_name = _get_app_root_dir(company_name, role_name)
    template_dir = os.path.join(engine_dir, 'templates')
    jinja_env = jinja2.Environment(loader=jinja2.FileSystemLoader(template_dir))

    def latex_escape(text):
        if not text: return ""
        text = str(text).replace('\\', r'\textbackslash{}')
        escape_chars = {
            '&': r'\&', '%': r'\%', '$': r'\$', '#': r'\#', '_': r'\_',
            '{': r'\{', '}': r'\}', '~': r'\textasciitilde{}',
            '^': r'\textasciicircum{}'
        }
        text = "".join(escape_chars.get(c, c) for c in text)
        return text.replace('\n', r'\\ ')

    def escape_data(obj):
        if isinstance(obj, str):
            return latex_escape(obj)
        elif isinstance(obj, dict):
            return {k: escape_data(v) for k, v in obj.items()}
        elif isinstance(obj, list):
            return [escape_data(i) for i in obj]
        return obj

    safe_data = escape_data(cv_data)
    personal_info = safe_data.get("personal_info", {})
    
    # Render CV
    template_cv = jinja_env.get_template('cv_template.tex')
    
    rendered_cv = template_cv.render(
        personal_info=personal_info,
        professional_summary=safe_data.get("professional_summary", ""),
        sections=safe_data.get("sections", [])
    )
    latex_dir = os.path.join(app_root_dir, "latex", "cv")
    os.makedirs(latex_dir, exist_ok=True)
    tex_path = os.path.join(latex_dir, f"{c_name}_CV.tex")
    with open(tex_path, "w", encoding="utf-8") as f:
        f.write(rendered_cv)
        
    try:
        subprocess.run(['pdflatex', '-interaction=nonstopmode', f"{c_name}_CV.tex"], cwd=latex_dir, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        compiled_pdf = os.path.join(latex_dir, f"{c_name}_CV.pdf")
        if os.path.exists(compiled_pdf):
            return compiled_pdf
    except subprocess.CalledProcessError:
        pass
    return None

def compile_cl_pdf(cl_paragraphs, personal_info, company_name, role_name):
    if not cl_paragraphs:
        return None
        
    app_root_dir, c_name = _get_app_root_dir(company_name, role_name)
    template_dir = os.path.join(engine_dir, 'templates')
    jinja_env = jinja2.Environment(loader=jinja2.FileSystemLoader(template_dir))
    
    def latex_escape(text):
        if not text: return ""
        text = str(text).replace('\\', r'\textbackslash{}')
        escape_chars = {
            '&': r'\&', '%': r'\%', '$': r'\$', '#': r'\#', '_': r'\_',
            '{': r'\{', '}': r'\}', '~': r'\textasciitilde{}',
            '^': r'\textasciicircum{}'
        }
        text = "".join(escape_chars.get(c, c) for c in text)
        return text.replace('\n', r'\\ ')
        
    template_cl = jinja_env.get_template('cl_template.tex')
    safe_paragraphs = [latex_escape(p) for p in cl_paragraphs]
    rendered_cl = template_cl.render(
        personal_info=personal_info,
        company_name=latex_escape(company_name),
        cover_letter_paragraphs=safe_paragraphs
    )
    
    latex_cl_dir = os.path.join(app_root_dir, "latex", "cover_letter")
    os.makedirs(latex_cl_dir, exist_ok=True)
    tex_cl_path = os.path.join(latex_cl_dir, f"{c_name}_CL.tex")
    with open(tex_cl_path, "w", encoding="utf-8") as f:
        f.write(rendered_cl)
        
    cl_template_root = os.path.join(root_dir, 'Generic_Cover_Letter_Template')
    cover_cls_src = os.path.join(cl_template_root, 'cover.cls')
    openfonts_src = os.path.join(cl_template_root, 'OpenFonts')
    if os.path.exists(cover_cls_src):
        shutil.copy2(cover_cls_src, os.path.join(latex_cl_dir, 'cover.cls'))
    if os.path.exists(openfonts_src):
        dest_fonts = os.path.join(latex_cl_dir, 'OpenFonts')
        if not os.path.exists(dest_fonts):
            shutil.copytree(openfonts_src, dest_fonts)
            
    try:
        subprocess.run(['xelatex', '-interaction=nonstopmode', f"{c_name}_CL.tex"], cwd=latex_cl_dir, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        compiled_cl = os.path.join(latex_cl_dir, f"{c_name}_CL.pdf")
        if os.path.exists(compiled_cl):
            return compiled_cl
    except subprocess.CalledProcessError:
        pass
    return None

def compiler_node(state: AgentState):
    tailored_cv = state.get("tailored_cv", {})
    app_root_dir, c_name = _get_app_root_dir(state["company_name"], state["role_name"])
    
    compiled_pdf = compile_cv_pdf(tailored_cv, state["company_name"], state["role_name"])
    if compiled_pdf:
        final_pdf_path = os.path.join(app_root_dir, f"Heishigan_Pathmaraj_CV_{c_name}.pdf")
        shutil.copy2(compiled_pdf, final_pdf_path)

    # Render Cover Letter
    personal_info = tailored_cv.get("personal_info", {})
    cl_paragraphs = state.get("cover_letter_paragraphs", [])
    if state.get("generate_cover_letter") and len(cl_paragraphs) > 0 and not state.get("cl_safety_failed", False):
        compiled_cl = compile_cl_pdf(cl_paragraphs, personal_info, state["company_name"], state["role_name"])
        if compiled_cl:
            final_cl_path = os.path.join(app_root_dir, f"Heishigan_Pathmaraj_Cover_Letter_{c_name}.pdf")
            shutil.move(compiled_cl, final_cl_path)
            
    return {}

def review_conditional(state: AgentState):
    if state["review_feedback"] == "PASS" or state["revision_count"] >= 3:
        return "pass"
    return "fail"



# --- BUILD GRAPH ---
# setup_node and strategist_node are called directly from gui.py as plain functions.
# Graph: tailor → reviewer → cover_letter → compiler
# Note: cl_reviewer removed (LLM critic was unreliable). Human review at the compiler
# interrupt is the quality gate for the cover letter.
memory = MemorySaver()
builder = StateGraph(AgentState)

builder.add_node("tailor", tailor_node)
builder.add_node("reviewer", reviewer_node)
builder.add_node("cover_letter", cover_letter_node)
builder.add_node("compiler", compiler_node)

builder.set_entry_point("tailor")
builder.add_edge("tailor", "reviewer")
builder.add_conditional_edges("reviewer", review_conditional, {
    "pass": "cover_letter",
    "fail": "tailor"
})
builder.add_edge("cover_letter", "compiler")
builder.add_edge("compiler", END)

# Pause before compiler for human review only.
app = builder.compile(checkpointer=memory, interrupt_before=["compiler"])
