"""remove_byok_api_key_column_and_add_used_trial_emails

Revision ID: 62ddd5fe166f
Revises: 6bcde8126f01
Create Date: 2026-07-21 09:11:52.296382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ddd5fe166f'
down_revision: Union[str, None] = '6bcde8126f01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_trial_emails',
    sa.Column('email_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('email_hash')
    )
    op.create_index(op.f('ix_used_trial_emails_email_hash'), 'used_trial_emails', ['email_hash'], unique=False)
    op.drop_column('user_profiles', 'encrypted_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('encrypted_api_key', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_used_trial_emails_email_hash'), table_name='used_trial_emails')
    op.drop_table('used_trial_emails')
    # ### end Alembic commands ###
